// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A fair price indicator AI agent.
 *
 * - getFairPrice - A function that suggests a fair price for a property based on its features, location, and current market trends.
 * - GetFairPriceInput - The input type for the getFairPrice function.
 * - GetFairPriceOutput - The return type for the getFairPrice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetFairPriceInputSchema = z.object({
  propertyFeatures: z
    .string()
    .describe('A detailed description of the property features, including size, number of rooms, amenities, and condition.'),
  locationDetails: z
    .string()
    .describe('Specific details about the property location, including neighborhood, proximity to amenities, and transportation options.'),
  marketTrends: z
    .string()
    .describe('Information about current market trends in the area, including average rental prices for similar properties.'),
});
export type GetFairPriceInput = z.infer<typeof GetFairPriceInputSchema>;

const GetFairPriceOutputSchema = z.object({
  suggestedPrice: z
    .number()
    .describe('The suggested fair price for the property, based on the provided information.'),
  priceJustification: z
    .string()
    .describe('A detailed explanation of why the suggested price is considered fair, based on the property features, location, and market trends.'),
});
export type GetFairPriceOutput = z.infer<typeof GetFairPriceOutputSchema>;

export async function getFairPrice(input: GetFairPriceInput): Promise<GetFairPriceOutput> {
  return getFairPriceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getFairPricePrompt',
  input: {schema: GetFairPriceInputSchema},
  output: {schema: GetFairPriceOutputSchema},
  prompt: `You are an expert real estate analyst specializing in determining fair rental prices for properties.

You will use the provided information about the property features, location details, and current market trends to suggest a fair rental price for the property.

Property Features: {{{propertyFeatures}}}
Location Details: {{{locationDetails}}}
Market Trends: {{{marketTrends}}}

Based on this information, provide a suggested rental price and a detailed explanation of why this price is considered fair.
`,
});

const getFairPriceFlow = ai.defineFlow(
  {
    name: 'getFairPriceFlow',
    inputSchema: GetFairPriceInputSchema,
    outputSchema: GetFairPriceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
